Dev 4.0.1
yogeshrnaik/camunda-external-task-client-python3 pull request #48
Opened 2021-06-26 23:13 UTC by behrensger

This small patch enables the Extension Properties from Camunda 7.15.
The interface description is here https://docs.camunda.org/manual/7.15/reference/rest/external-task/fetch/ (grep for "includeExtensionProperties" on this side)

The extension properties are reachable in the Camunda Modeler Tool as a tab in the Properties Panel. I use these properties to model a kind of constants in the workflow.

Interestingly, your code already works with properties, the only thing missing is the message to Camunda "send the properties" as part of a task.

includeExtensionProperties=True means that the  properties will be sent by default for people who use the default config and won't be sent for older projects with an overridden configuration.

2021-06-27 05:01 UTC, yogeshrnaik commented on camunda/variables/properties.py
> +        return prop
```suggestion
        return self.properties.get(property_name, None)
```
this should be sufficient. not need to check None

2021-06-27 05:02 UTC, yogeshrnaik approved these changes
Approved with one comment

2021-06-27 05:03 UTC, yogeshrnaik requested changes
Pls fix one review comment and failed test case

2021-06-28 04:32 UTC, yogeshrnaik commented on camunda/client/external_task_client.py
> +                if "includeExtensionProperties" in self.config else False
```suggestion
                "includeExtensionProperties": self.config.get("includeExtensionProperties") or False
```

2021-06-28 04:33 UTC, yogeshrnaik submitted a review, later dismissed

2021-06-28 04:34 UTC, yogeshrnaik approved these changes

2021-06-28 13:20 UTC, behrensger commented
Hi Naik, 
you approved the PR. As far as I understand do you also have to do a merge. I cannot do the merge since I have no rights on your repository.
Kind Regards

2021-06-28 13:45 UTC, merged

2021-06-28 13:45 UTC, yogeshrnaik commented
> Hi Naik,
> you approved the PR. As far as I understand do you also have to do a merge. I cannot do the merge since I have no rights on your repository.
> Kind Regards

@behrensger I have merged your PR. Thank you for your contribution.